# three things: A label when the workflow will run, what jobs will run.

name: My CI Workflow

on:
  push:

jobs:
  hello:
    name: My Hello Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello!"

  goodbye:
    name: My Goodbye Job
    needs: hello
    runs-on: windows-latest
    steps:
      - run: echo "Goodbye!"
